--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.791.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 3/16/2022 13:49:52
-- Server version: 10.4.22
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

DROP DATABASE IF EXISTS trapland;

CREATE DATABASE trapland
	CHARACTER SET utf8
	COLLATE utf8_hungarian_ci;

--
-- Set default database
--
USE trapland;

--
-- Create table `username`
--
CREATE TABLE username (
  ID INT(11) NOT NULL AUTO_INCREMENT,
  Username VARCHAR(255) DEFAULT NULL,
  Password VARCHAR(255) DEFAULT NULL,
  ReachedLevel INT(11) DEFAULT NULL,
  Active INT(2) DEFAULT NULL,
  PRIMARY KEY (ID)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

--
-- Create table `stats`
--
CREATE TABLE stats (
  Username_ID INT(11) DEFAULT NULL,
  Level INT(11) DEFAULT NULL,
  Time TIME DEFAULT NULL,
  DeathCounter INT(11) DEFAULT NULL
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 16384,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

-- 
-- Dumping data for table username
--
-- Table trapland.username does not contain any data (it is empty)

-- 
-- Dumping data for table stats
--
INSERT INTO stats VALUES
(1, 1, '01:54:46', 100);

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;